kind: Pod
apiVersion: v1
metadata:
  name: openafsapp
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-csi-volume
      persistentVolumeClaim:
        claimName: openafs-pvc # defined in csi-pvc.yaml
