apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openafs-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openafs-csi-sc # defined in csi-storageclass.yaml
