apiVersion: v1
kind: PersistentVolume
metadata:
        name: openafs-static-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: afscsi.openafs.org
    volumeHandle: "/afs/pn/GlobalCSIMnt/yadayada"
