kind: Pod
apiVersion: v1
metadata:
 name: openafsstaticapp1
spec:
 containers:
   - name: my-frontend
     image: centos
     volumeMounts:
     - mountPath: /data
       name: my-csi-volume
     command: [ "sleep", "1000000" ]
   - name: ticket-refresh
     image: kinitimage:latest
     imagePullPolicy: IfNotPresent
     env:
     - name: CELLNAME
       value: "punetest.in.ibm.com"
     - name: REFRESH_TIME
       value: "20"
     volumeMounts:
     - mountPath: /etc/afs
       name: secret-ticket
     - mountPath: /etc/config
       name: config-volume
     command: [ "/rekinit.sh" ]
     
 volumes:
   - name: my-csi-volume
     persistentVolumeClaim:
       claimName: openafs-pvc # defined in csi-pvc.yaml
   - name: secret-ticket
     secret:
       secretName: afs-refresh-tok
   - name: config-volume
     configMap:
       name: openafs-config
