apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: openafscsiapps.afscsi.openafs.org
spec:
  group: afscsi.openafs.org
  names:
    kind: OpenafsCSIApp
    listKind: OpenafsCSIAppList
    plural: openafscsiapps
    singular: openafscsiapp
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: OpenafsCSIApp is the Schema for the openafscsiapps API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: OpenafsCSIAppSpec defines the desired state of OpenafsCSIApp
            properties:
              provisionerSpec:
                description: Provisioner spec
                properties:
                  provisionerName:
                    description: Name of a provisioner
                    type: string
                  provisionerNameSpace:
                    description: Namespace of a provisioner
                    type: string
                  provisionerImageName:
                    description: Provisioner Image name
                    type: string
                type: object    
              attacherSpec:
                description: Provisioner spec
                properties:
                  attacherName:
                    description: Name of a attacher
                    type: string
                  attacherNameSpace:
                    description: Namespace of a attacher
                    type: string
                  attacherImageName:
                    description: Provisioner Image name
                    type: string
                type: object    
              pluginSpec:
                description: Plugin spec
                properties:
                  pluginName:
                    description: Name of a plugin
                    type: string
                  pluginNameSpace:
                    description: Namespace of a plugin
                    type: string
                  pluginImage:
                    description: Plugin Image name
                    type: string
                  driverRegistrarImage:
                    description: driverRegistrar Image name
                    type: string
                  livenessProbeImage:
                    description: livenessProbe Image name
                    type: string
                  afsMount:
                    description: AFS mount
                    type: string
                  configmap:
                    description: AFS Configuration
                    type: string
                type: object    
            type: object
          status:
            description: OpenafsCSIAppStatus defines the observed state of OpenafsCSIApp
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
